name: lms_login_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0 
  flutter_inappwebview: ^6.0.0
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2  # Add this
  http_parser: ^4.0.2   # Add this for multipart
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/GD-logo.png